### ISSUE TITLE
EmailTemplateEntity.Messages -> MList notification of parent Issue (Entity.GetParentEntity())

### ISSUE THREAD

**Issue by modma** [signumsoftware/extensions#102]
Hi, another problem with a Migration of my project, in this case is the work of the extensions parsing the `MList` notification, in my scenario:  
```
tempBlah = new EmailTemplateEntity
                {
                    Active = true,
                    Name = "Liquidaciones Blah",
                    From = new EmailTemplateContactEntity
                    {
                        DisplayName = "Blah Hispania",
                        EmailAddress = "blah@blah.es"
                    },
                    StartDate = DateTime.Now.TrimToMinutes(),
                    IsBodyHtml = true,
                    SystemEmail = SystemEmailLogic.ToSystemEmailEntity(typeof(LiquidacionesColaboradoresMail)),
                    Query = QueryLogic.GetQueryEntity(typeof(SettlementEntity)),
                    Messages =
                    {
                        new EmailTemplateMessageEntity(CultureInfoLogic.GetCultureInfoEntity("es"))
                        {
                            //Template = tempAMV,
                            Subject = "Informe Blah @[Entity.CreationDate.Date]",
                            Text = @"<p>Estimado @[Supplier.FiscalEntity.FiscalName],<p><br/> Blah Blah"
                        }
                    }
                }.Save();
            }
```
the `Messages` validation at `Save()` causes 2 referece null exceptions in `Subject` & `Text`, this errors is caused in `EmailTemplateLogic.EmailTemplateMessageText_StaticPropertyValidation` at `message.GetParentEntity()` because the `MList<>` is not transfered the parent entity...
A bad test fix with i made to test the problem is this modification of `EmailTemplateEntity.Messages` this this code (old framework system usage)
```
		[NotNullable]
		MList<EmailTemplateMessageEntity> messages;
		[NotifyCollectionChaMessages nged, NotifyChildProperty]
        public MList<EmailTemplateMessageEntity> Messages
        {
            get
            {
                if (messages == null) Messages = new MList<EmailTemplateMessageEntity>();
                return messages;
            }
            set { Set(ref messages, value); }
        }
```
in bad practice now corrects the notification, but seems a potencial bug in the framework parsing the `.SetParentEntity()` in the `MList`...

any effective solution? thanks

![error](https://cloud.githubusercontent.com/assets/16271691/23995275/1a21b442-0a49-11e7-8d5f-81b3d9dfa4fd.gif)

**Comment by olmobrutall** [comment]
If you look at ModifiableEntity, the attribute `NotifyChildPropertyAttribute` controls setting the ParentEntity. 

Looks like `Messages` already has this attribute so in theory should work. Are you in the very last version? 

...maybe with this tip you can debug the problem and fin the issue?

**Comment by modma** [comment]
yes, I integrated the lastest framework & extensions in the application this morning, to test if recentlies changes of the extensions (a week aprox), fixes it this problem, of course the problem still remains

**Comment by olmobrutall** [comment]
Found! look at DashboardEntity, it has a special constructor that calls RebindEvents. EmailTemplateEntity needs the same. 

Don't know why this bug doesn't cause problems in our code... 

Can you check it and make a PR? 

Thanks

**Comment by modma** [comment]
Yes, effectively this code fixed the problem, i'll create a PR in a momet adding this:
```
        public EmailTemplateEntity()
        {
            **_RebindEvents();_**
        }

        public EmailTemplateEntity(object queryName) : _**this()**_
        {
            this.queryName = queryName;
        }
```
Last thing, explicitly in with cases, besides this, needs to add `RebindEvents();`? thanks

**Comment by olmobrutall** [comment]
This is the order of execution when constructing an entity: 
* ModifiableEntity field initializarions
* ModifiableEntity constructor (calls RebindEvents)
* EmailTemplateEntity field initialization
* EmailTemplateEntity constructor

So when RebindEvents is called, the fields in the descendent classes are not set. 

So until someone comes with a better solution, classes with MLists and NotifyChildProperty need RevindEvents

**Comment by modma** [comment]
ok i publish the PR, thank you very much!
PD: saludos de parte de Adrian y Nuria

**Comment by olmobrutall** [comment]
Thanks for the PR and writing the issue in English

PD: Hey, saludos a los tres :)
