### ISSUE TITLE
ScheduledTasks scheduling 

### ISSUE THREAD

**Issue by ze-german** [signumsoftware/extensions#319]
We have discovered a strange behaviour exhibited by the task scheduling system.

![image](https://user-images.githubusercontent.com/1737134/52798749-d89eb800-3078-11e9-82e5-33de8f5904d3.png)

this chart is showing scheduled start-time (the x-Axis) vs actual start-time on the y-Axis.
As you can see there are two sets of tasks, one supposed to start at 1AM one at 2AM.

both mostly start during their scheduled hours, but there are lots of cases, where a task has started much later during the day.

**Comment by olmobrutall** [comment]
You have system event logs, maybe the server was down?

**Comment by olmobrutall** [comment]
I mean SystemEventLogEntity

**Comment by ze-german** [comment]
Apparently the Application shuts down when there is no traffic, and starts up at ~1AM and shuts down a couple of minutes later.


![systemeventlog](https://user-images.githubusercontent.com/1737134/52948897-0dfa1d00-337b-11e9-9f1c-24c4e5e771ff.jpg)

**Comment by ze-german** [comment]
i've disabled iis shutting down the worker process.
I'll see what happens

**Comment by olmobrutall** [comment]
Great to know, running processes in IIS has this issues, on the other side is quite convinient. 

I close the issue for now :)
